#ifndef GGLEX
#define GGLEX(X, Y)
#endif

GGLEX("vi8", vi8)
GGLEX("vi16", vi16)
GGLEX("vi32", vi32)
GGLEX("vi64", vi64)
GGLEX("vu8", vu8)
GGLEX("vu16", vu16)
GGLEX("vu32", vu32)
GGLEX("vu64", vu64)
GGLEX("vch", vch)
GGLEX("vr32", vr32)
GGLEX("vr64", vr64)
GGLEX("void", void)
GGLEX("fn", function)
GGLEX("struct", struct)
GGLEX("variant", variant)
GGLEX("enum", enum)
GGLEX("const", const)
GGLEX("if", if)
GGLEX("else", else)
GGLEX("for", for)
GGLEX("while", while)
GGLEX("do", do)
GGLEX("switch", switch)
GGLEX("case", case)
GGLEX("return", return)
GGLEX("break", break)
GGLEX("continue", continue)
GGLEX("operator", operator)
GGLEX("static_cast", static_cast)
GGLEX("reinterpret_cast", reinterpret_cast)
GGLEX("const_cast", const_cast)
GGLEX("ckx_cast", ckx_cast)
GGLEX("ckx", ckx)
GGLEX("sizeof", sizeof)
