#ifndef GGLEX
#define GGLEX(X, Y)
#endif

GGLEX("vi8", int8)
GGLEX("vi16", int16)
GGLEX("vi32", int32)
GGLEX("vi64", int64)
GGLEX("vu8", uint8)
GGLEX("vu16", uint16)
GGLEX("vu32", uint32)
GGLEX("vu64", uint64)
GGLEX("vch", char)
GGLEX("vr32", real32)
GGLEX("vr64", real64)
GGLEX("void", void)
GGLEX("function", function)
GGLEX("struct", struct)
GGLEX("variant", variant)
GGLEX("enum", enum)
GGLEX("const", const)
GGLEX("if", if)
GGLEX("for", for)
GGLEX("while", while)
GGLEX("do", do)
GGLEX("switch", switch)
GGLEX("case", case)
GGLEX("return", return)
GGLEX("break", break)
GGLEX("continue", continue)
GGLEX("operator", operator)
GGLEX("ckx", ckx)
